---
# tasks file for acl
- name: include distribution tasks
  ansible.builtin.include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}.yml"
  loop_control:
    loop_var: loop_distribution
  tags:
    - configuration
    - packages

- name: Setup ACL information.
  ansible.posix.acl:
    path: "{{ item.path }}"
    default: "{{ item.default | default(omit) }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    follow: "{{ item.follow | default(omit) }}"
    permissions: "{{ item.permissions }}"
    state: "{{ item.state }}"
    recursive: "{{ item.recursive | default(omit) }}"
  loop: "{{ acl_config }}"
  loop_control:
    label: "{{ item.path }}"
